/* ============================================================================
 * Anchor — library6.js
 * Bonus recipe pack: more weeknight + comfort + global options so a long-term
 * user never runs dry on variety. Loaded after library5.js.
 * ==========================================================================*/
(function (Anchor) {
  "use strict";

  var MORE = [
    {
      id: "red-beans-rice", name: "Red Beans & Rice", emoji: "🍚",
      category: "dinner", gear: "cook", servings: 6,
      protein: 20, fiber: 14, carbs: 62, fat: 8, calories: 430, cost: 0.85, prepMin: 45, batch: true,
      tags: ["cheap", "high-fiber", "freezes", "one-pot"],
      ingredients: ["2 cans red beans (or dried)", "Onion, pepper, celery, garlic", "Cajun spice, bay", "Rice", "Optional sausage"],
      steps: ["Soften the trinity.", "Add beans + spices + water; simmer until creamy.", "Serve over rice."],
      booster: "oil", note: "Louisiana cheap-eats classic. Mash some beans for creaminess.",
    },
    {
      id: "minestrone", name: "Minestrone", emoji: "🍲",
      category: "dinner", gear: "cook", servings: 6,
      protein: 16, fiber: 13, carbs: 50, fat: 8, calories: 360, cost: 1.00, prepMin: 40, batch: true,
      tags: ["cheap", "vegetarian", "high-fiber", "freezes", "one-pot"],
      ingredients: ["2 cans beans", "Small pasta", "Carrot, celery, onion, zucchini", "Tomato + stock", "Parmesan rind, herbs"],
      steps: ["Soften veg base.", "Add tomato, stock, beans; simmer.", "Add pasta near the end."],
      booster: "cheese", note: "The ultimate use-up-the-veg soup; freezes beautifully.",
    },
    {
      id: "tofu-tikka", name: "Tofu Tikka Masala", emoji: "🍛",
      category: "dinner", gear: "cook", servings: 4,
      protein: 22, fiber: 6, carbs: 44, fat: 18, calories: 470, cost: 1.40, prepMin: 30,
      tags: ["vegetarian", "high-protein"],
      ingredients: ["Tofu (or chicken)", "Onion-tomato masala", "Yogurt or coconut milk", "Garam masala, paprika", "Rice"],
      steps: ["Crisp tofu.", "Simmer a creamy spiced tomato sauce.", "Fold in tofu; serve over rice."],
      booster: "oil", note: "Takeaway favorite, made cheap and protein-forward.",
    },
    {
      id: "huevos-rancheros", name: "Huevos Rancheros", emoji: "🍳",
      category: "breakfast", gear: "cook", servings: 2,
      protein: 24, fiber: 11, carbs: 38, fat: 18, calories: 440, cost: 1.10, prepMin: 12,
      tags: ["high-protein", "high-fiber"],
      ingredients: ["Tortillas", "Refried/black beans", "Fried eggs", "Salsa, cheese, avocado"],
      steps: ["Warm tortillas + beans.", "Top with fried eggs, salsa, cheese.", "Avocado if you have it."],
      booster: "avocado", note: "A breakfast that actually keeps you full till lunch.",
    },
    {
      id: "tabbouleh-chickpea", name: "Chickpea Tabbouleh", emoji: "🥗",
      category: "lunch", gear: "floor", servings: 3,
      protein: 14, fiber: 11, carbs: 40, fat: 14, calories: 360, cost: 0.95, prepMin: 12,
      tags: ["no-cook", "high-fiber", "vegetarian", "make-ahead"],
      ingredients: ["Bulgur or couscous", "1 can chickpeas", "Parsley, mint, tomato, cucumber", "Lemon + olive oil"],
      steps: ["Soak bulgur.", "Mix with chickpeas, herbs, veg, dressing.", "Better after it sits."],
      booster: "oil", note: "Herby, fresh, high-fiber make-ahead lunch.",
    },
    {
      id: "dahl-baked-potato", name: "Dal-Loaded Baked Potato", emoji: "🥔",
      category: "dinner", gear: "cook", servings: 2,
      protein: 18, fiber: 13, carbs: 64, fat: 8, calories: 420, cost: 0.80, prepMin: 20,
      tags: ["cheap", "high-fiber", "vegetarian", "uses-leftovers"],
      ingredients: ["Baked potatoes", "Leftover dal or canned lentils + spice", "Yogurt", "Cilantro, chili"],
      steps: ["Bake/microwave potatoes.", "Split + load with warm dal.", "Top with yogurt + herbs."],
      booster: "oil", note: "Two cheap staples become a genuinely great dinner.",
    },
    {
      id: "chicken-noodle-soup", name: "Chicken Noodle Soup (from carcass)", emoji: "🍜",
      category: "dinner", gear: "cook", servings: 6,
      protein: 24, fiber: 5, carbs: 42, fat: 10, calories: 360, cost: 0.90, prepMin: 50, batch: true,
      tags: ["cheap", "freezes", "one-pot", "uses-leftovers"],
      ingredients: ["Roast chicken carcass + leftover meat", "Carrot, celery, onion", "Noodles", "Herbs, bay"],
      steps: ["Simmer carcass + veg for stock.", "Strain; add meat + noodles + fresh veg.", "Free soup from 'trash'."],
      booster: "oil", note: "The payoff for saving Friday's roast-chicken bones.",
    },
    {
      id: "veggie-frittata", name: "Loaded Veggie Frittata (batch)", emoji: "🍳",
      category: "breakfast", gear: "cook", servings: 6,
      protein: 16, fiber: 3, carbs: 8, fat: 12, calories: 190, cost: 0.70, prepMin: 30, batch: true,
      tags: ["high-protein", "make-ahead", "low-carb"],
      ingredients: ["8 eggs", "Whatever veg + cheese", "Potato optional", "Herbs"],
      steps: ["Whisk eggs, fold in veg + cheese.", "Bake in a pan/dish 190°C/375°F ~25 min.", "Slice; reheats all week."],
      booster: "cheese", note: "Cut into wedges for grab-and-go protein breakfasts.",
    },
    {
      id: "peanut-stew", name: "West African Peanut Stew", emoji: "🥜",
      category: "dinner", gear: "cook", servings: 6,
      protein: 18, fiber: 11, carbs: 46, fat: 18, calories: 470, cost: 1.10, prepMin: 40, batch: true,
      tags: ["cheap", "vegetarian", "dense-calories", "freezes", "one-pot"],
      ingredients: ["Peanut butter + tomato base", "Chickpeas + sweet potato", "Onion, garlic, ginger, chili", "Spinach, rice"],
      steps: ["Build a tomato-peanut base.", "Add chickpeas + sweet potato; simmer.", "Wilt spinach; serve over rice."],
      booster: "pb", note: "Rich, dense, gain-friendly, and deeply cheap. Freezes great.",
    },
    {
      id: "tuna-rice-cakes", name: "Tuna Rice Cake Stacks", emoji: "🍙",
      category: "lunch", gear: "floor", servings: 1,
      protein: 24, fiber: 3, carbs: 26, fat: 10, calories: 300, cost: 1.10, prepMin: 4,
      tags: ["no-cook", "high-protein", "fast"],
      ingredients: ["Rice cakes", "Tuna + yogurt/mayo", "Cucumber, sriracha"],
      steps: ["Mix tuna.", "Pile on rice cakes with cucumber + sriracha."],
      booster: "oil", note: "Crunchy, 24g protein, zero cooking.",
    },
    {
      id: "halloumi-bowl", name: "Halloumi & Chickpea Bowl", emoji: "🧀",
      category: "dinner", gear: "cook", servings: 2,
      protein: 26, fiber: 10, carbs: 38, fat: 22, calories: 510, cost: 1.80, prepMin: 18,
      tags: ["vegetarian", "high-protein"],
      ingredients: ["Halloumi, pan-fried", "Chickpeas, roasted", "Couscous/rice", "Lemon, herbs, chili"],
      steps: ["Crisp halloumi + chickpeas.", "Serve over grain with lemon + herbs."],
      booster: "oil", note: "Salty, satisfying, vegetarian protein bomb.",
    },
    {
      id: "miso-noodle-soup", name: "Miso Noodle Soup + Egg", emoji: "🍜",
      category: "lunch", gear: "cook", servings: 1,
      protein: 22, fiber: 5, carbs: 50, fat: 12, calories: 420, cost: 1.10, prepMin: 10,
      tags: ["warm", "fast", "no-appetite-friendly"],
      ingredients: ["Noodles", "Miso + stock", "Soft-boiled egg", "Frozen veg, tofu, scallion"],
      steps: ["Cook noodles + veg in stock.", "Off heat, whisk in miso.", "Top with egg + scallion."],
      booster: "oil", note: "Cozy, fast, and easy to get down on a low-appetite day.",
    },
    {
      id: "bean-quinoa-chili", name: "Three-Bean Quinoa Chili", emoji: "🌶️",
      category: "dinner", gear: "cook", servings: 6,
      protein: 22, fiber: 17, carbs: 58, fat: 9, calories: 430, cost: 1.10, prepMin: 35, batch: true,
      tags: ["cheap", "vegetarian", "high-fiber", "freezes", "one-pot"],
      ingredients: ["3 cans beans", "Quinoa", "Tomato, corn", "Onion, garlic, chili spices"],
      steps: ["Build chili base.", "Add beans, quinoa, tomato, water; simmer 25 min.", "Quinoa thickens it + adds protein."],
      booster: "cheese", note: "17g fiber, complete protein from quinoa + beans.",
    },
    {
      id: "pita-pizza", name: "Pita Pizzas (batch a few)", emoji: "🍕",
      category: "snack", gear: "cook", servings: 2,
      protein: 18, fiber: 5, carbs: 36, fat: 14, calories: 360, cost: 1.00, prepMin: 10,
      tags: ["fast", "kid-in-you"],
      ingredients: ["Pita/English muffins", "Sauce + mozzarella", "Any topping"],
      steps: ["Top pitas.", "Bake/toast ~7 min."],
      booster: "cheese", note: "Pizza craving, portioned and quick.",
    },
    {
      id: "yogurt-bark-pb", name: "PB-Banana Frozen Bites", emoji: "🍌",
      category: "snack", gear: "floor", servings: 8,
      protein: 6, fiber: 2, carbs: 14, fat: 8, calories: 130, cost: 0.30, prepMin: 8, batch: true,
      tags: ["no-cook", "make-ahead", "dense-calories", "sweet"],
      ingredients: ["Banana coins", "Peanut butter", "Dark chocolate drizzle"],
      steps: ["Sandwich PB between banana coins.", "Freeze.", "Grab for a dense sweet bite."],
      booster: "pb", note: "Frozen, sweet, calorie-dense — gain-friendly treat.",
    },
    {
      id: "savory-protein-bowl", name: "Cottage Cheese 'Nacho' Bowl", emoji: "🧀",
      category: "snack", gear: "floor", servings: 1,
      protein: 26, fiber: 4, carbs: 18, fat: 9, calories: 270, cost: 1.00, prepMin: 3,
      tags: ["no-cook", "high-protein", "savory"],
      ingredients: ["Cottage cheese", "Salsa + a little cheese", "Tortilla chips or veg to dip"],
      steps: ["Top cottage cheese with salsa + cheese.", "Scoop with chips/veg."],
      booster: "oil", note: "Nacho-ish craving, 26g protein, two minutes.",
    },
  ];
  Array.prototype.push.apply(Anchor.meals, MORE);

  Object.assign(Anchor.recipeLinks, {
    "red-beans-rice": [{ source: "Budget Bytes", title: "Red beans & rice", url: "https://www.budgetbytes.com/?s=red+beans+and+rice" }],
    "minestrone": [{ source: "Budget Bytes", title: "Minestrone", url: "https://www.budgetbytes.com/?s=minestrone" }],
    "tofu-tikka": [{ source: "BBC Good Food", title: "Tikka masala", url: "https://www.bbcgoodfood.com/search?q=tikka%20masala" }],
    "peanut-stew": [{ source: "Budget Bytes", title: "Peanut stew", url: "https://www.budgetbytes.com/?s=peanut+stew" }],
    "minestrone-2": [],
    "chicken-noodle-soup": [{ source: "Budget Bytes", title: "Chicken noodle soup", url: "https://www.budgetbytes.com/?s=chicken+noodle+soup" }],
    "huevos-rancheros": [{ source: "Budget Bytes", title: "Huevos rancheros / salsa eggs", url: "https://www.budgetbytes.com/?s=huevos+rancheros" }],
    "bean-quinoa-chili": [{ source: "Budget Bytes", title: "Quinoa chili", url: "https://www.budgetbytes.com/?s=quinoa+chili" }],
  });
})(window.Anchor = window.Anchor || {});
